"""added additional discount, gender, type column to items table

Revision ID: 4df1da7133a8
Revises: 377deab5bc05
Create Date: 2024-08-20 22:03:18.422372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4df1da7133a8'
down_revision: Union[str, None] = '377deab5bc05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('stock', sa.Integer(), server_default='0', nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('img_url', sa.String(), server_default='https://modde.com/item_placeholder.png', nullable=False),
    sa.Column('discount', sa.Integer(), server_default='0', nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('added_by', sa.Integer(), server_default='2', nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_foreign_key(None, 'cart_items', 'items', ['item_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.drop_table('items')
    # ### end Alembic commands ###
