"""empty message

Revision ID: 9583c0f23d96
Revises: 83fb05eeff99
Create Date: 2024-08-18 22:41:34.372446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9583c0f23d96'
down_revision: Union[str, None] = '83fb05eeff99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('img_url', sa.String(), server_default='https://modde.com/item_placeholder.png',
                                     nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'img_url')
    # ### end Alembic commands ###
