"""added new updated_at column to sales table

Revision ID: aafedba6c43c
Revises: fbeea2b60cfc
Create Date: 2024-08-25 18:58:46.472493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aafedba6c43c'
down_revision: Union[str, None] = 'fbeea2b60cfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'updated_at')
    # ### end Alembic commands ###
