"""added primary key + foreign key constrains for cart_items table

Revision ID: d621a91cb4cb
Revises: 4df1da7133a8
Create Date: 2024-08-20 22:15:10.996356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd621a91cb4cb'
down_revision: Union[str, None] = '4df1da7133a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
